Dokumente/Fit4AF_Berger/Rails/Projekte/flix/config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'

  resource :session
  resources :users
  
  resources :movies do
    resources :reviews
  end



end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :reviews, dependent: :destroy

	validates :title, presence: {message: ": Das Feld muss ausgefüllt sein"}
	validates :released_on, presence: {message: ": Das Feld muss ausgefüllt sein"}
	validates :duration, presence: {message: ": Das Feld muss ausgefüllt sein"}
	validates :description, length: {minimum: 25, message:": Die Beschreibung muss mindestens 25 Zeichen lang sein!"}
	validates :total_gross, numericality: {greater_than_or_equal_to: 0, message:": Die Einnahmen müssen größer oder gleich 0 sein!"}
	validates :poster_image_file, allow_blank: true, format: { with: %r{.(gif|jpg|png)}, message:": Das Bild muss vom Format .gif .jpg oder .png sein!"}
	validates :rating, inclusion:  { in: %w(G PG PG-13 R NC-17), message:": Der Film muss das Rating G, PG, PG-13, R oder NC-17"}

	def flop?
		total_gross < 150000 unless total_gross.blank?
	end

	def self.shown
		where("released_on <= ?", Time.now).order("released_on")
	end

	def self.total_gross
		where("total_gross >= 100000000")
	end
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie

  FILM_RATING = [1, 2, 3, 4, 5]
	validates :stars, inclusion: { in: FILM_RATING }
	validates :comment, presence: true
	validates :name, presence: true
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, format: /\A\S+@\S+\z/, uniqueness: {case_sensitive: false}
  
  def self.authenticate(email, password)
  	user = User.find_by(email: email)
  	user && user.authenticate(password)
  end
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	before_action :set_sidebar_movies

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

private

  def set_sidebar_movies
		@sidebar_movies = Movie.total_gross
	end

end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :set_movie, only: [:show, :edit, :update, :destroy]
	
	def index
		@movies = Movie.shown
	end

	def show
		@reviews = Review.where(params[:id])
	end

	def new
		@movie = Movie.new
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			flash[:notice] = "Erfolgreich gespeichert."
			redirect_to movies_url
		else
		render :new
		end
	end

	def edit
	end

	def update
		@movie.update(movie_params)
		if @movie.save
			redirect_to movies_url, notice: "movie successful edited!"
		else
			render :edit
		end
	end

	def destroy
		@movie.destroy
		redirect_to movies_url, alert: "movie successful deleted!"
	end

	private
		def movie_params
			params.require(:movie).permit(:poster_image_file, :director, :cast, :duration, :title, :description, :total_gross, :rating, :released_on)
		end

		def set_movie
			@movie = Movie.find(params[:id])
		end

end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_movie
	def index
		@reviews = @movie.reviews
	end

	def new
		@review = @movie.reviews.new
	end

	def create
		@review = @movie.reviews.new(review_params)
		if @review.save
			redirect_to movie_path(@movie.id), notice: "Die Bewertung wurde gespeichert"
		else
			render :new, notice: "Fehler beim Speichern"
		end
	end

	def show
		@review = Review.find(params[:id])
	end

	def destroy
		@review = Review.find(params[:id])
		@review.delete
		redirect_to movie_reviews_url(@movie.id), alert: "Bewertung von #{@review.name} erfolgreich gelöscht"
	end

	private
		def review_params
			params.require(:review).permit(:name, :stars, :comment, :movie_id)
		end
		def set_movie
			@movie = Movie.find(params[:movie_id])
		end

end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

  def create
    if user = User.authenticate(params[:email], params[:password])
    	session[:user_id] = user.id
    	flash[:notice] = "Hey BOY, back again"
    	redirect_to user
    else
      flash.now[:alert] = "Email nicht gefunden oder falsches Passwort"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Bye, bye."
  end
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/helpers/application_helper.rb
module ApplicationHelper

	def flop_top(var)
		if var.flop?
			"FLOP!"
		else
			number_to_currency(var.total_gross, unit: " € ")
		end 
	end

	def stars(stars)
		if movie.poster_image_file.blank?
			image_tag("dummy.jpg")
		else
			image_tag(movie.poster_image_file)
		end
	end

end
	

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/helpers/movies_helper.rb
module MoviesHelper
	def image_for(movie)
		if movie.poster_image_file.blank?
			image_tag("dummy.jpg")
		else
			image_tag(movie.poster_image_file)
		end
	end
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/helpers/sessions_helper.rb
module SessionsHelper
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/helpers/users_helper.rb
module UsersHelper
end

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <li><%= link_to "Alle Filme", movies_path %></li>
    </ul>
    <ul class="right">
      <% if current_user %>
      <li><%= link_to current_user.name, user_path(current_user.id) %></li>
      |
      <li><%= link_to "SignOut", session_path, method: :delete %></li>
      <% else %>
    	<li><%= link_to "SignIn", signin_path %></li> | 
      <li><%= link_to "SignUp", signup_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/layouts/_sidebar.html.erb
<h4>BlockBuster</h4>
<ul class="side-nav">
  <% @sidebar_movies.each do |movie| %>
				<li><%= link_to movie.title, movie_path(movie.id)%></li>
	<% end%>
</ul>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Flix" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Flix" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row">
      <%= render 'layouts/navigation' %>
      <div class="row">
        <div class="medium-3 columns">
          <%= render "layouts/sidebar" %>
        </div>
        <div class="medium-9 columns">
           <%= render 'layouts/messages' %>
           <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
	<%= render "shared/errors", object: @movie %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
		<p>
		<%= f.label :rating %><br>
		<%= f.text_field :rating %>
	</p>
		<p>
		<%= f.label :total_gross %><br>
		<%= f.number_field :total_gross %>
	</p>
	<p>
		<%= f.label :released_on %><br>
		<%= f.datetime_select :released_on %>
	</p>
	<p>
		<%= f.label :poster_image_file %><br>
		<%= f.text_field :poster_image_file, placeholder: "Filmtitel + .jpg als Dateityp" %>
	</p>
	<p>
		<%= f.label :cast %><br>
		<%= f.text_field :cast %>
	</p>
	<p>
		<%= f.label :director %><br>
		<%= f.text_field :director %>
	</p>
	<p>
		<%= f.label :duration %><br>
		<%= f.number_field :duration %>
	</p>

		<p>
		<%= f.submit %>
	</p>
<% end %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/movies/edit.html.erb
<h2>Editieren von <%= @movie.title %></h2>

	<%= render "form" %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/movies/index.html.erb
		<% if @movies.size == 1 %>
			<h1>Movie</h1>
		<% else %>
			<h1>Movies</h1>
		<% end %> 

<table border=1>
	<thead>
		<tr>
			<th>Title</th>
			<th>Release</th>
			<th>Beschreibung</th>
			<th>Rating</th>
			<th>Total gross</th>
			<th>Reviews</th>
			<th>Show</th>
			<th>Edit</th>
			<th>Del</th>
		</tr>
	</thead>
	<tbody>
		<% @movies.each do |movie| %>
			<tr>
				<td><%= movie.title %></td>
				<td><%= movie.released_on %></td>

				<td><%= truncate(movie.description, length: 40, sepeterator: '') %></td>
				<td><%= movie.rating %></td>
				<td><%= flop_top(movie) %></td>
				<td><%= link_to "<i class='fi-results-demographics icon-blue'></i>".html_safe, movie_reviews_path(movie.id) %></td>
				<td><%= link_to "<i class='fi-video icon-green'></i>".html_safe, movie_path(movie.id) %></td>
				<td><%= link_to "<i class='fi-wrench icon-blue'></i>".html_safe, edit_movie_path(movie.id) %></td>
				<td><%= link_to "<i class='fi-trash icon-red'></i>".html_safe, movie_path(movie.id), method: :delete, data: {confirm: "Wirklich löschen"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

<%= link_to "Neuen Movie anlegen", new_movie_path %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/movies/new.html.erb
<h3>Neuer Movie</h3>

	<%= render "form" %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>

<p><%= @movie.description %></p>

<%= image_for(@movie) %>
<p>
	<h3>Wann</h3>
	<%= @movie.released_on %>

	<h3>Worum geht's?</h3>
	<%= @movie.description %>

	<h3>Bewertung</h3>
	<%= @movie.rating %>

	<h3>Einspielergebnis</h3>
	<%= @movie.total_gross %>

	<h3>Lauflänge</h3>
 <%= pluralize(@movie.duration, 'minute') %>

 <h3>Regisseur</h3>
 <%= @movie.director %>

 <h3>Besetzung</h3>
 <%= @movie.cast %>
</p>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Sterne</th>
			<th>Kommentar</th>
		</tr>
	</thead>
	<tbody>
		<% @reviews.each do |review| %>
			<tr>
				<td><%= review.name %></td>
				<td><%= review.stars %></td>
				<td><%= link_to "<i class='fi-magnifying-glass icon-green'></i>".html_safe, movie_review_path(@movie.id, review.id) %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<p>
	<div class="button-group">
		<%= link_to "Alle Movies anzeigen", movies_path, class: "button" %>
		<%= link_to "Back", request.referer, class: "button" %>
		<%= link_to "Film bewerten!", new_movie_review_path(@movie.id), class: "button" %>
	</div>
</p>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <% if @user.new_record? %>
    <% #if controller.action_name == 'new' %>
    <%= f.submit 'Create Account'%>
    <% else %>
    <%= f.submit 'Update Account' %>
    <% end %>
  </div>
<% end %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

Dokumente/Fit4AF_Berger/Rails/Projekte/flix/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>